### PR TITLE
Py3k Support

### PR DESCRIPTION
**Pull request by clebergnu**
These add a bunch of changes/fixes necessary to get inspektor running on Python 3.

### CODE REVIEW

**Comment by clebergnu** [comment]
@jnmnus thanks spotting the typos.  I'll wait for a second review (requested one from @lmr) to send a v2.

**Comment by clebergnu** [comment]
[inspektor: py3k compatibility](https://trello.com/c/GL0WVsgv/1020-inspektor-py3k-compatibility)

**Comment by lmr** [comment]
Sure, I'll get to it tomorrow morning, thanks!

**Comment by lmr** [comment]
@clebergnu this is straightforward enough, looks good and works, I'll merge it. I can fix the typos afterwards.

**Pull request merged**
